[project]
name = "prtsc_timer"
version = "1.0.0"
description = "Take a screenshot after a countdown"
readme = "README.md"
authors = [
    { name = "nasimhuq", email = "nasim.huq@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
prtsc_timer = "prtsc_timer.app:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
